name: main

on:
  push:
    branches: [master]    
  pull_request:
    branches: [master]
  workflow_dispatch:  

env:
  ProjectName: SealedClass_Console

jobs:
 
  micro-benchmark-tests:   
    uses: ./.github/workflows/micro-benchmark-test.yaml
    secrets: inherit
    with:      
      Mean: 400000

